src/OSR4Rights.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using Azure.ResourceManager.Network.Models;
using Microsoft.AspNetCore.Mvc;
using Serilog;

namespace OSR4Rights.Web.Pages
{
    public class IndexModel : PageModel
    {
        public string? HSText { get; set; }
        public string? HSScore { get; set; }
        public string? HSPrediction { get; set; }

        public string? AAText { get; set; }
        public string? AAGuid { get; set; }

        public string? CacheBust { get; set; }

        public async Task<IActionResult> OnGet(string? route, string? q)
        {
            var base64Guid = Convert.ToBase64String(Guid.NewGuid().ToByteArray());
            CacheBust = base64Guid;

            if (route == "hate")
            {
                Log.Information($"route is hate");
                q ??= "This is really not hate speech, even though I said hate";

                // call webservice
                // http://hmsoftware.org/hs
                // POST 
                // { "text":"dave is an awesome dude!" }

                var httpClient = new HttpClient();
                var url = "https://hmsoftware.org/hs";
                var data = new HSDto { Text = q };

                try
                {
                    var response = await httpClient.PostAsJsonAsync(url, data);
                    var foo = await response.Content.ReadFromJsonAsync<HSDto>();

                    HSText = foo.Text;
                    HSScore = foo.Score;
                    HSPrediction = foo.Prediction;

                }
                catch (Exception ex)
                {
                    HSText = "Sorry there was a problem - please try again later";
                    HSScore = "";
                    HSPrediction = "";
                    Log.Error($"Problem with HS webservice {ex}");
                }
            }

            else if (route == "auto")
            {
                Log.Information($"route is auto");
                q ??= "https://twitter.com/dave_mateer/status/1505876265504546817";

                var httpClient = new HttpClient();
                var url = "http://hmsoftware.org/api/aa";

                if (!ValidateUrl(q))
                {
                    AAText = $"Please check url: {q}";
                    return Page();
                }


                try
                {
                    var data = new AADto { url = q };
                    var response = await httpClient.PostAsJsonAsync(url, data);
                    var foo = await response.Content.ReadFromJsonAsync<AADto>();

                    AAText = "Processing";
                    AAGuid = foo.guid.ToString();
                    // redirect to aaresults
                    return LocalRedirect($"/aaresults/{foo.guid}");


                }
                catch (Exception ex)
                {
                    AAText = "Sorry there was a problem - please try again later";
                    Log.Error($"Problem with AA webservice {ex}");
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPost(string q)
        {
            q ??= "https://twitter.com/dave_mateer/status/1505876265504546817";

            var httpClient = new HttpClient();
            var url = "http://hmsoftware.org/api/aa";

            if (!ValidateUrl(q))
            {
                AAText = $"Please check url: {q}";
                return Page();
            }

            try
            {
                var data = new AADto { url = q };
                var response = await httpClient.PostAsJsonAsync(url, data);
                var foo = await response.Content.ReadFromJsonAsync<AADto>();

                AAText = "Processing";
                AAGuid = foo.guid.ToString();
                // redirect to aaresults
                return LocalRedirect($"/aaresult/{foo.guid}");


            }
            catch (Exception ex)
            {
                AAText = "Sorry there was a problem - please try again later";
                Log.Error($"Problem with AA webservice {ex}");
            }
            // PRG
            return Page();
        }


        private bool ValidateUrl(string url)
        {
            //Uri validatedUri;

            if (Uri.TryCreate(url, UriKind.Absolute, out Uri validatedUri)) //.NET URI validation.
            {
                //If true: validatedUri contains a valid Uri. Check for the scheme in addition.
                return (validatedUri.Scheme == Uri.UriSchemeHttp || validatedUri.Scheme == Uri.UriSchemeHttps);
            }
            return false;
        }

    }

    class AADto
    {
        public Guid? guid { get; set; }
        public string? url { get; set; }
        public string? cdn_url { get; set; }
        public string? screenshot { get; set; }
        public string? thumbnail { get; set; }
        public string status { get; set; }
    }

    class HSDto
    {
        public string Text { get; set; }
        public string? Score { get; set; }
        public string? Prediction { get; set; }
    }
}

src/OSR4Rights.Web/Pages/aaresult.cshtml.cs
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace OSR4Rights.Web.Pages
{
    //[Authorize(Roles = "Tier1, Tier2, Admin")]
    public class AAResultModel : PageModel
    {
        public AADto aadto { get; set; }

        //public async Task<IActionResult> OnPost(Guid aaguid)
        //{
           
        //}

        public async Task OnGet(Guid aaguid)
        {
            // query webservice to find out status
            var httpClient = new HttpClient();
            var url = $"http://hmsoftware.org/api/aa/{aaguid}";

            try
            {
                var data = new AADto { guid = aaguid };
                AADto? response = await httpClient.GetFromJsonAsync<AADto>(url);

                aadto = response;
                //AAText = "Processing";
                //AAGuid = foo.guid.ToString();

            }
            catch (Exception ex)
            {
                //AAText = "Sorry there was a problem - please try again later";
                Log.Error($"Problem with AA webservice {ex}");
            }
            //return Page();
            //var isAllowed = false;
            //foreach (var claim in User.FindAll(ClaimTypes.Role))
            //{
            //    if (claim.Value == "Tier2") isAllowed = true;
            //    else if (claim.Value == "Admin") isAllowed = true;
            //}

            //IsAllowedToUpload = isAllowed;
            //return Page();
        }

        public class AADto
        {
            public Guid? guid { get; set; }
            public string? url { get; set; }
            public string? cdn_url { get; set; }
            public string? screenshot { get; set; }
            public string? thumbnail { get; set; }
            public string status { get; set; }
        }

    }

}

src/OSR4Rights.Web/Pages/aaresults.cshtml.cs
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace OSR4Rights.Web.Pages
{
    //[Authorize(Roles = "Tier1, Tier2, Admin")]
    public class AAResultsModel : PageModel
    {
        public AADto aadto { get; set; }

        public async Task OnGet(Guid aaguid)
        {
            // query webservice to find out status
            var httpClient = new HttpClient();
            var url = $"http://hmsoftware.org/api/aa/{aaguid}";

            try
            {
                var data = new AADto { guid = aaguid };
                AADto? response = await httpClient.GetFromJsonAsync<AADto>(url);

                aadto = response;
                //AAText = "Processing";
                //AAGuid = foo.guid.ToString();

            }
            catch (Exception ex)
            {
                //AAText = "Sorry there was a problem - please try again later";
                Log.Error($"Problem with AA webservice {ex}");
            }

            //var isAllowed = false;
            //foreach (var claim in User.FindAll(ClaimTypes.Role))
            //{
            //    if (claim.Value == "Tier2") isAllowed = true;
            //    else if (claim.Value == "Admin") isAllowed = true;
            //}

            //IsAllowedToUpload = isAllowed;
        }

        public class AADto
        {
            public Guid? guid { get; set; }
            public string? url { get; set; }
            public string? cdn_url { get; set; }
            public string? screenshot { get; set; }
            public string? thumbnail { get; set; }
            public string status { get; set; }
        }

    }

}

src/OSR4Rights.Web/Pages/auto-archiver.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace OSR4Rights.Web.Pages
{
    //[Authorize(Roles = "Tier1, Tier2, Admin")]
    public class AutoArchiverModel : PageModel
    {
        public bool IsAllowedToUpload { get; set; }

        public void OnGet()
        {
            var isAllowed = false;
            foreach (var claim in User.FindAll(ClaimTypes.Role))
            {
                if (claim.Value == "Tier2") isAllowed = true;
                else if (claim.Value == "Admin") isAllowed = true;
            }

            IsAllowedToUpload = isAllowed;
        }

        // For user file uploads javascript handles the post

        // Sample data buttons
        // notice the TIER1 suffix on filenames

        //public IActionResult OnPostRunFlac() =>
        //    LocalRedirect($"/speech-parts-go?createdFileName=test_vocal_aTIER1.flac");

        //public IActionResult OnPostRunMp3() =>
        //            LocalRedirect($"/speech-parts-go?createdFileName=test_vocal_aTIER1.mp3");

        //public IActionResult OnPostRunMp4() =>
        //            LocalRedirect($"/speech-parts-go?createdFileName=test_vocal_aTIER1.mp4");
    }
}

src/OSR4Rights.Web/Pages/downloads.cshtml.cs
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.Extensions.Hosting;
using Serilog;

namespace OSR4Rights.Web.Pages
{
    // User has to be logged in (authenticated) and have an assigned Role (they get Tier1 after clicked on their email address confirm email)
    [Authorize(Roles = "Tier1, Tier2, Admin")]
    public class DownloadsModel : PageModel
    {
        private readonly IHostEnvironment _hostEnvironment;

        public DownloadsModel(IHostEnvironment hostEnvironment) => _hostEnvironment = hostEnvironment;

        public async Task<IActionResult> OnGet(int jobId, string fileName)
        {
            // /downloads directory is not in wwwroot so the static file serving can never hit it
            //var filePath = Path.Combine(_hostEnvironment.ContentRootPath, "downloads", jobId.ToString(), fileName);

            var filePath = Path.Combine("/mnt/osrshare/", "downloads", jobId.ToString(), fileName);

            // Is this Login allowed to look at this jobId?
            var loginId = Helper.GetLoginIdAsInt(HttpContext);

            // Does the requested file exist on filesystem?
            var exists = System.IO.File.Exists(filePath);
            if (!exists)
            {
                Log.Warning($"{filePath} requested which was not found by loginId {loginId}. Application problem?");
                return NotFound();
            }

            var connectionString = AppConfiguration.LoadFromEnvironment().ConnectionString;
            var isAllowed = await Db.CheckIfLoginIdIsAllowedToViewThisJobId(connectionString, loginId, jobId);

            if (!isAllowed)
            {
                Log.Warning($"loginId {loginId} who is authorised and has a role, requested jobId {jobId} filename {fileName} which they don't have access to");
                // todo it would be nice to preserve the url which is denied.
                return LocalRedirect("/account/access-denied");
            }

            //Log.Information($"Successful download request for jobId: {jobId} filename: {fileName} by loginId {loginId}");

            // Get the content type which could be html, csv, zip
            var provider = new FileExtensionContentTypeProvider();

            if (!provider.TryGetContentType(fileName, out string contentType)) contentType = "application/octet-stream";

            // why is this returning a 304?
            return PhysicalFile(filePath, contentType);
        }
    }
}

src/OSR4Rights.Web/Pages/face-search.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace OSR4Rights.Web.Pages
{
    //[Authorize(Roles = "Tier1, Tier2, Admin")]
    public class FaceSearchModel : PageModel
    {
        public bool IsAllowedToUpload { get; set; }

        public void OnGet()
        {
            var isAllowed = false;
            foreach (var claim in User.FindAll(ClaimTypes.Role))
            {
                if (claim.Value == "Tier2") isAllowed = true;
                else if (claim.Value == "Admin") isAllowed = true;
            }
            IsAllowedToUpload = isAllowed;
        }

        // For user file uploads javascript handles the post

        // Sample data buttons
        public IActionResult OnPostRun1Barack() => 
            LocalRedirect($"/face-search-go?createdFileName=1barackTIER1.zip");

        public IActionResult OnPostRun6lfwsmall() => 
            LocalRedirect($"/face-search-go?createdFileName=6lfwsmallTIER1.zip");
    }
}

src/OSR4Rights.Web/Pages/faq.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OSR4Rights.Web.Pages
{
    public class FaqModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/OSR4Rights.Web/Pages/hate-speech.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace OSR4Rights.Web.Pages
{
    //[Authorize(Roles = "Tier1, Tier2, Admin")]
    public class HateSpeechModel : PageModel
    {
        public bool IsAllowedToUpload { get; set; }

        public void OnGet()
        {
            var isAllowed = false;
            foreach (var claim in User.FindAll(ClaimTypes.Role))
            {
                if (claim.Value == "Tier2") isAllowed = true;
                else if (claim.Value == "Admin") isAllowed = true;
            }

            IsAllowedToUpload = isAllowed;
        }

        // For user file uploads javascript handles the post

        // Sample data buttons
        // notice the TIER1 suffix on filenames
        public IActionResult OnPostRunTE1() =>
            LocalRedirect($"/hate-speech-go?createdFileName=x1TE1TIER1.csv");

        public IActionResult OnPostRunTESTfile() =>
            LocalRedirect($"/hate-speech-go?createdFileName=x2TESTfileTIER1.csv");

        public IActionResult OnPostRunMultiLingualTest() =>
                LocalRedirect($"/hate-speech-go?createdFileName=x3multilingual-testTIER1.csv");
    }
}

src/OSR4Rights.Web/Pages/health-check.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;

namespace OSR4Rights.Web.Pages
{
    // Check webserver is alive (uptimerobot)
    // https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class HealthCheckModel : PageModel { }
}

src/OSR4Rights.Web/Pages/privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OSR4Rights.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/OSR4Rights.Web/Pages/speech-parts.cshtml.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace OSR4Rights.Web.Pages
{
    //[Authorize(Roles = "Tier1, Tier2, Admin")]
    public class SpeechPartsModel : PageModel
    {
        public bool IsAllowedToUpload { get; set; }

        public void OnGet()
        {
            var isAllowed = false;
            foreach (var claim in User.FindAll(ClaimTypes.Role))
            {
                if (claim.Value == "Tier2") isAllowed = true;
                else if (claim.Value == "Admin") isAllowed = true;
            }

            IsAllowedToUpload = isAllowed;
        }

        // For user file uploads javascript handles the post

        // Sample data buttons
        // notice the TIER1 suffix on filenames

        public IActionResult OnPostRunFlac() =>
            LocalRedirect($"/speech-parts-go?createdFileName=test_vocal_aTIER1.flac");

        public IActionResult OnPostRunMp3() =>
                    LocalRedirect($"/speech-parts-go?createdFileName=test_vocal_aTIER1.mp3");

        public IActionResult OnPostRunMp4() =>
                    LocalRedirect($"/speech-parts-go?createdFileName=test_vocal_aTIER1.mp4");
    }
}

src/OSR4Rights.Web/Pages/dec-test.cshtml
@page
@model DecTestModel
@{
    ViewData["Title"] = "Dec Test";
}
<h1>@ViewData["Title"]</h1>

<p>Dec test</p>

<form method="post">
    <input asp-for="Email" style="width: 300px;" value="davemateer@gmail.com">

    <button type="submit" class="btn btn-primary">Send</button>
</form>

src/OSR4Rights.Web/Pages/downloads.cshtml
@page "{jobId:int}/{fileName}"
@model OSR4Rights.Web.Pages.DownloadsModel
@{
}

src/OSR4Rights.Web/Pages/face-search.cshtml
@page
@model OSR4Rights.Web.Pages.FaceSearchModel
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor
@{
    ViewData["Title"] = "Face Search";
}
@* bootstrap for tus progress bar*@
@section Styles {
<link href="/css/style-login.css" rel="stylesheet" type="text/css" />
@*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />*@
}

<div class="container-tool">
    <h2 class="text-xl">FaceSearch</h2>

    <p>Looks for a target face which you give as an image, in many other images. </p>

    <p>This is designed as a first pass to help human rights investigators - let this tool process many images and narrow down the most likely ones for investigators to look at</p>

    <!-- not logged in -->
    @if (!_httpContextAccessor.HttpContext!.User.Identity!.IsAuthenticated)
    {
        <h2 class="text-md py-md">If you wouldn't mind...</h2>

        <p class="">Please Tell Us who you are by <a href="/account/register">Registering</a> then you can run the samples</p>

        <p class="py-sm">Or <a href="/account/login">Login</a> if you have already registered</p>

        <img src="img/fs.jpg" alt="">

    }
    else
    {
        <!-- tier 2 -->
        @if (Model.IsAllowedToUpload)
        {
            <p>Please upload a zip file containing 2 folders</p>
            <ul class="normal-ul">
                <li>/search directory which contains images to search</li>
                <li>/target directory which contains target image(s)</li>
            </ul>

            <!-- keep for now as js code still references-->
            <input type="text" id="endpoint" name="endpoint" value="/files/" hidden="true">
            <input type="number" id="paralleluploads" name="paralleluploads" value="1" hidden="true">
            <input type="number" id="chunksize" name="chunksize" hidden="true">

            <div class="py-md">
                <label for="upload-photo" class="btn btn-blue file-upload">Choose File</label>
                <input type="file" id="upload-photo">
            </div>


            <!-- https://stackoverflow.com/questions/11235206/twitter-bootstrap-form-file-element-upload-button-->
            <!-- file button -->
            @*        <label class="btn btn-default">
                <input type="file">
                </label>
            *@
            <div class="progress" style="height: 32px;">
                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><span id="foo"></span></div>
            </div>

            <!-- pause / resume button-->
            <div class="py-md">
                <button class="btn btn-sm btn-outline-info" id="toggle-btn" hidden="true"></button>
            </div>

            <p>If your upload is interrupted, come back to this page and try again. It will try to resume the upload. We use the <a href="https://tus.io/">tus.io</a> open protocol.</p>
            <br />
        }
        else
        {
            <!-- tier 1-->
            <p class="text-danger">We need to manually approve you before you can upload your own files. Please try the samples below</p>
        }

        <h4 id="samples">Samples</h4>

        <p class="py-md">
            1. <a href="/sample-data/facesearch/1barack.zip">barack.zip</a> 10 images with target is Barack Obama which is a 7KB headshot
        </p>

        <form method="post" asp-page-handler="run1barack">
            <input type="submit" class="btn btn-light" value="Run Barack Sample" />
        </form>

        <p class="py-md">2. <a href="/sample-data/facesearch/6lfwsmall.zip">lfwsmall.zip</a> A subset of <a href="http://vis-www.cs.umass.edu/lfw/">Labeled Faces in the Wild</a> 145 images</p>

        <form method="post" asp-page-handler="run6lfwsmall">
            <input type="submit" class="btn btn-light" value="Run LFW Sample" />
        </form>

        <br />

        <h4>Screenshots</h4>
        <p class="py-md">Here is the output of the Barack sample</p>

        <img src="/screenshots/facesearch/1barack.jpg" asp-append-version="true" />

        <h1>Background</h1>

        <p>.png, .jpg, .jpeg supported</p>

        <p>Multiple target images supported</p>

        <p>Large zip filesizes are supported - we have tested up to 1.6GB. Please email support@osr4rights-tools.org if you have problems and need a different way to upload securely the files. </p>


        <p>Model is trained for adults. It is not as good on childrens faces</p>


        <h1>Security</h1>
        <p>We do not store any of your uploaded zip files.</p>

        <p>The VM where raw images are processed is deleted soon after your jobs are finished.</p>

        <p>To download results you need to login with your approved email address</p>

        <h1>Technical</h1>

        <p>A first job takes at a minimum 3 minutes to run. It runs on a Microsoft Azure GPU based virtual machine so needs time to initialise. Subsequent jobs are much faster</p>

        <p>Based on the <a href="https://github.com/ageitgey/face_recognition#usage">face_recognition</a> open source library which uses the <a href="http://dlib.net/">dlib</a> toolkit's state-of-the-art facial recognition algorithms. The model has an accuracy of 99.38% on the <a href="http://vis-www.cs.umass.edu/lfw/">Label Faces in the Wild</a> benchmark</p>
    }
</div>

@*  </div>
    </section>*@

@section Scripts {
@*<partial name="_ValidationScriptsPartial" />*@

@* jquery needed for tus script - todo refactor out*@
<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>

<script src="~/js/tus-js-client/dist/tus.js" asp-append-version="true"></script>
<script src="~/js/upload-tus.js" asp-append-version="true"></script>
}

src/OSR4Rights.Web/Pages/health-check.cshtml
@page
@model HealthCheckModel
@{
    Layout = "";
}
Healthy

src/OSR4Rights.Web/Pages/speech-parts.cshtml
@page
@model OSR4Rights.Web.Pages.SpeechPartsModel
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor
@{
    ViewData["Title"] = "Speech Parts";
}

@* bootstrap for tus progress bar*@
@section Styles {
@*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />*@
<link href="/css/style-login.css" rel="stylesheet" type="text/css" />
}

<div class="container-tool">
    <h2 class="text-xl">Speech Parts</h2>

    <p class="py-md">Upload a Video or Audio file and to find only the sections with English speech. We then give you back only those sections as a WAV file. For example CCTV footage looking for only the sections with talking. </p>

    <p>We have successfully tested up to</p>

    <ul class="normal-ul">
        <li>30 mins, 800MB mp4 video</li>
        <li>1 hour, 174MB video</li>
        <li>9 hour, 393MB video</li>
    </ul>
    <!-- not logged in -->
    @if (!_httpContextAccessor.HttpContext!.User.Identity!.IsAuthenticated)
    {
        <h2 class="text-md py-md">If you wouldn't mind...</h2>

        <p class="">Please Tell Us who you are by <a href="/account/register">Registering</a> then you can run the samples</p>

        <p class="py-sm">Or <a href="/account/login">Login</a> if you have already registered</p>

        <img src="img/sp.jpg" alt="">

    }
    else
    {
        <!-- tier 2-->
        @if (Model.IsAllowedToUpload)
        {
            <p>Please upload a file of any of these types</p>
            <ul class="normal-ul">
                <li>mp4 (video)</li>
                <li>webm (video)</li>
                <li>mp3</li>
                <li>ogg</li>
                <li>flac</li>
                <li>m4a</li>
                <li>wav</li>
            </ul>
            <!-- keep for now as js code still references-->
            <input type="text" id="endpoint" name="endpoint" value="/files/" hidden="true">
            <input type="number" id="paralleluploads" name="paralleluploads" value="1" hidden="true">
            <input type="number" id="chunksize" name="chunksize" hidden="true">

            <br />
            <!-- file button -->
            <!-- have got a css name clash with bootstrap but I've put mine further down in _Layout so it takes precedence -->
            <label for="upload-photo" class="btn btn-blue file-upload">Choose File</label>
            <input type="file" id="upload-photo">

            <br />
            <br />

            <div class="progress" style="height: 32px;">
                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><span id="foo"></span></div>
            </div>

            <br />
            <!-- pause / resume button-->
            <button class="btn btn-sm btn-outline-info" id="toggle-btn" hidden="true"></button>

            <br />
        }
        else
        {
            <!-- tier 1-->
            <p class="text-danger">We need to manually approve you before you can upload your own files. Please try the samples below</p>
        }

        <br />

        <h1 id="samples">Samples</h1>

        <p>Please feel free to try any of the following samples <a href="/sample-data/speechparts/test_vocal_a.zip">test_vocal_a.zip</a> (this is all the samples below) </p>

        <p class="py-md"> Flac audio example - some vocal, some noise </p>
        <p>
            <form method="post" asp-page-handler="runFlac">
                <input type="submit" class="btn btn-light" value="Run test_vocal_a.flac" />
            </form>
        </p>

        <p class="py-md">mp3 audio example - some vocal, some noise </p>
        <p>
            <form method="post" asp-page-handler="runMp3">
                <input type="submit" class="btn btn-light" value="Run test_vocal_a.mp3" />
            </form>
        </p>

        <p class="py-md"> mp4 video example - some vocal, some noise </p>
        <p>
            <form method="post" asp-page-handler="runMp4">
                <input type="submit" class="btn btn-light" value="Run test_vocal_a.mp4" />
            </form>
        </p>


        @*

            <p>2. <a href="/sample-data/hatespeech/x2TESTfile.csv">x2TESTfile.csv</a> Almost 300 English text samples</p>

            <p>
            <form method="post" asp-page-handler="runTESTfile">
            <input type="submit" value="Run x2TESTfile.csv" />
            </form>
            </p>


            <p>3. <a href="/sample-data/hatespeech/x3multilingual-test.csv">x3multilingual-test.csv</a> A small set containing English, Arabic and Russian text </p>

            <p>
            <form method="post" asp-page-handler="runmultilingualtest">
            <input type="submit" value="Run x3multilingual-test.csv" />
            </form>
            </p>*@

        <h1 class="py-md">Further Information</h1>

        <p>Please see the article on <a href="https://davemateer.com">here</a> for more technical details</p>

    }
</div>

@section Scripts {
@*<partial name="_ValidationScriptsPartial" />*@

@* jquery needed for tus script - todo refactor out*@
<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>

<script src="~/js/tus-js-client/dist/tus.js" asp-append-version="true"></script>
<script src="~/js/upload-tus.js" asp-append-version="true"></script>
}